# Copyright 2022 Cerebras Systems.
#
# Licensed under the Apache License, Version 2.0 (the 'License');
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an 'AS IS' BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#BERT-Base, max seq length 128

### Input
train_input:
    data_processor: 'BertTfRecordsProcessor'
    data_dir: [
        './input/pubmed/pubmed_baseline/tfrecord/uncased_msl128_mp20_wwm_dupe5/train',
        './input/pubmed/pubmed_daily_update/tfrecord/uncased_msl128_mp20_wwm_dupe5/train',
        './input/pubmed/pubmed_fulltext/tfrecord/uncased_msl128_mp20_wwm_dupe5/train'
    ]
    vocab_file: '../../vocab/uncased_pubmed_abstracts_and_fulltext_vocab.txt'
    max_sequence_length: 128
    max_predictions_per_seq: 20  # maximum number of masked LM predictions per sequence.
    batch_size: 1024

eval_input:
    data_processor: 'BertTfRecordsProcessor'
    data_dir: [
        './input/pubmed/pubmed_baseline/tfrecord/uncased_msl128_mp20_wwm_dupe5/test',
        './input/pubmed/pubmed_daily_update/tfrecord/uncased_msl128_mp20_wwm_dupe5/test',
        './input/pubmed/pubmed_fulltext/tfrecord/uncased_msl128_mp20_wwm_dupe5/test'
    ]
    vocab_file: '../../vocab/uncased_pubmed_abstracts_and_fulltext_vocab.txt'
    max_sequence_length: 128
    max_predictions_per_seq: 20  # maximum number of masked LM predictions per sequence.
    batch_size: 64

model:
    # Embedding
    hidden_size: 768
    use_position_embedding: True
    use_segment_embedding: True
    position_embedding_type: 'learned' # {'learned', 'fixed'}
    max_position_embeddings: 512
    share_embedding_weights: True

    # Encoder
    num_hidden_layers: 12
    dropout_rate: 0.1
    layer_norm_epsilon: 1e-5

    # Encoder - Attention
    num_heads: 12
    attention_dropout_rate: 0.1

    # Encoder - ffn
    filter_size: 3072
    encoder_nonlinearity: 'gelu'
    use_ffn_bias: True

    weight_initialization_seed: 0

    use_vsl: True
    mixed_precision: True
    boundary_casting: False
    tf_summary: False

### Optimization
optimizer:
    optimizer_type: 'adam' # {'sgd', 'momentum', 'adam', 'adamw'}
    epsilon: 1e-6
    max_gradient_norm: 1.0
    disable_lr_steps_reset: True
    learning_rate:
        - steps: 80000
          scheduler: 'Linear'
          initial_learning_rate: 0.0
          end_learning_rate: 0.0001
        - scheduler: 'Linear'
          initial_learning_rate: 0.0001
          end_learning_rate: 0.0
          steps: 800000
    loss_scaling_factor: 'dynamic'

runconfig:
    save_summary_steps: 100
    save_checkpoints_steps: 10000
    keep_checkpoint_max: 0
    max_steps: 720000
    enable_distributed: False
    model_dir: 'model_dir'
    cs_ip:
    mode: 'train'
    multireplica: False
